#!/bin/bash

set -euo pipefail

retry() {
  local retries=$1; shift
  local delay=$1; shift
  local attempts=1

  until "$@"; do
    retry_exit_status=$?
    echo "Exited with $retry_exit_status" >&2
    if (( retries == "0" )); then
      return $retry_exit_status
    elif (( attempts == retries )); then
      echo "Failed $attempts retries" >&2
      return $retry_exit_status
    else
      echo "Retrying $((retries - attempts)) more times..." >&2
      attempts=$((attempts + 1))
      sleep "$delay"
    fi
  done
}

# Creates an in-memory credential cache for git, and populates it with the kibanamachine token for 15 minutes for https requests to github
{
  KIBANAMACHINE_TOKEN="$(retry 5 15 gcloud secrets versions access latest --secret=kibana-buildkite-kibanamachine)"
  git config --global credential.helper store
  echo "protocol=https
host=github.com
username=token
password=$KIBANAMACHINE_TOKEN" | git credential-store store
}

export DOCKER_BUILDKIT=1
