#!/bin/bash

set -euo pipefail

# There's some code in the kibana repository that depends on kibana being checked out to a directory named "kibana"
if [[ "$BUILDKITE_REPO" == *"/kibana.git" ]]; then
  export BUILDKITE_BUILD_CHECKOUT_PATH="$BUILDKITE_BUILD_CHECKOUT_PATH/kibana"
fi
